version: '3'
services:

  #:
  build-python35:
    image: hon:python35
    build:
      context: .
      args:
        - PYTHON_VERSION=3.5.10
    environment:
      - PYTHON_VERSION=3.5.10
    volumes:
      - .:/usr/src/hon

  #: 
  build-python36:
    image: hon:python36
    build:
      context: .
      args:
        - PYTHON_VERSION=3.6.13
    environment:
      - PYTHON_VERSION=3.6.13
    volumes:
      - .:/usr/src/hon

  #:
  build-python37:
    image: hon:python37
    build:
      context: .
      args:
        - PYTHON_VERSION=3.7.10
    environment:
      - PYTHON_VERSION=3.7.10
    volumes:
      - .:/usr/src/hon

  #:
  build-python38:
    image: hon:python38
    build:
      context: .
      args:
        - PYTHON_VERSION=3.8.8
    environment:
      - PYTHON_VERSION=3.8.8
    volumes:
      - .:/usr/src/hon