version: '3'
services:

  #:
  build-python35:
    image: hon:python35
    build:
      context: .
      dockerfile: ./infrastructure/python3.5/Dockerfile
    entrypoint: /github-build.sh
    volumes:
      - .:/usr/src/hon

  #: 
  build-python36:
    image: hon:python36
    build:
      context: .
      dockerfile: ./infrastructure/python3.6/Dockerfile
    entrypoint: /github-build.sh
    volumes:
      - .:/usr/src/hon

  #:
  build-python37:
    image: hon:python37
    build:
      context: .
      dockerfile: ./infrastructure/python3.7/Dockerfile
    entrypoint: /github-build.sh
    volumes:
      - .:/usr/src/hon